{{- if eq (include "elasticsearch.authProvider" .) "basic-authentication"}}
apiVersion: v1
kind: Secret
metadata:
  name: srs-elastic-credentials
type: kubernetes.io/basic-auth
data:
  username: {{ template "elasticsearchBasicAuthNUsername" . }}
  password: {{ template "elasticsearchBasicAuthNPassword" . }}
{{end}}

