{{ $depName := printf "%s" (include "deploymentName" $) }}
{{ if (eq (include "performDeployment" $) "true") }}
{{ range $index, $dep := .Values.global.tier}}
{{ template "pega.config" dict "root" $ "dep" $dep "name" (printf "%s-%s" $depName $dep.name)}}
{{ end }}
{{ end }}