{{ $depName := printf "%s" (include "deploymentName" $) }}

{{ if (eq (include "performDeployment" $) "true") }}
{{ range $dep := .Values.global.tier  }}
{{ if ($dep.hpa) }}
{{ template "pega.hpa" dict "root" $ "name" (printf "%s-hpa" (printf "%s-%s" $depName $dep.name)) "deploymentName" (printf "%s-%s" $depName $dep.name) "hpa" $dep.hpa }}
{{ end }}
{{ end }}
{{ end }}