---
image: "YOUR_HAZELCAST_IMAGE:TAG"
imagePullPolicy: "Always"
# Enter the number of initial members in hazelcast cluster.
replicas: 3
# Setting below to true will deploy the infinity in client server hazelcast mode
enabled: false
# username to be used in client server hazelcast mode for authentication
username: ""
# password to be used in client server hazelcast mode for authentication
password: ""

# Memory and CPU settings for HZ service
resources:
  requests:
    memory: "2Gi"
    cpu: 2
  limits:
    memory: "4Gi"
    cpu: 2
# client settings for hazelcast
client:
  clusterName: "PRPC"
# Server side settings for hazelcast
server:
  java_opts: "-XX:MaxRAMPercentage=80.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/hazelcast/logs/heapdump.hprof
  -XX:+UseParallelGC -Xlog:gc*,gc+phases=debug:file=/opt/hazelcast/logs/gc.log:time,pid,tags:filecount=5,filesize=3m"
  min_cluster_size: "3"
  jmx_enabled: "true"
  health_monitoring_level: "OFF"
  operation_generic_thread_count: ""
  operation_thread_count: ""
  io_thread_count: ""
  event_thread_count: ""
  max_join_seconds: ""
  group_name: "PRPC"
  mancenter_url: ""
  graceful_shutdown_max_wait_seconds: "600"
  service_dns_timeout: ""
  logging_level: "info"
  diagnostics_enabled: "true"
  diagnostics_metric_level: "info"
  diagnostic_log_file_size_mb: "50"
  diagnostics_file_count: "3"
